### ISSUE TITLE
Link data on court cases

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#14] opened 2017-03-14 10:48 UTC
- [ ] Highlight link to court cases and blacklist in documentation or About or FAQ.
- [ ]  404 page not found when clicking on detail link to court cases.

**Comment by mireille-raad** [comment] 2017-04-27 15:51
https://github.com/anjesh/moldova-open-contracting-data-challenges/wiki/Data-Challenges

**Comment by anjesh** [comment] 2017-05-25 03:06
As discussed the day before, we have updated the code to scrape the data from 15+ sites (there were be around 50 court sites). And they have also updated their site, and included pdf content in the source file itself, rather than link https://cac.instante.justice.md/ro/hot. It means that we need to download these files (which are in html format) locally. The last run took around 12+ hours and 17 GB of data, causing out-of-space issue in 20GB VPS - breaking the scrapping process. Do you think this is worth the effort from long term perspective, the content still needs to be cleaned-up for names to identify with the contractors? 

thoughts? @dc-coder

**Comment by mireille-raad** [comment] 2017-05-25 14:58
Let me talk with the team and get back to you. 

My personal suggestions is that we should just have the documentation for how to do this manully and highlight what you just said and they are free to do it if they want or not. (they need to resize their server and know the implications) - maybe this process is done once or twice a year.

By providing the documentation and saying that we can't do this automatically because of the implications on their server... instead of marking this deliverable as "not done" we mark it as "complete"

We can also add in the documentation a recommendation on how they can make this process more manageable and part of their bigger data strategy (I am happy to do this write up with tin)

**Comment by anjesh** [comment] 2017-05-26 04:27
Sure, that sounds good. We will update the codebase to include the code and document the process. Also i just saw that the server provided to us by egov has only 20GB space, so it's not possible to do this in their existing server. We will write the guidance.

**Comment by anjesh** [comment] 2017-05-31 08:36
We have created a new repo https://github.com/younginnovations/moldova-courtcases to handle the scrapping of courtcases with instructions on how to run. The courtcases API is accessible internally at localhost:8090 and used by the Moldova OpenContracting Portal to display the court cases information for a given company. We didn't link with the court-case file as the size is too huge around 17GB (not complete yet) to include in the existing server.

**Comment by bezunakarmi** [comment] 2017-05-31 12:06
Code has been updated to view the court cases. You can have a look at http://moldova-demo.yipl.com.np/contracts/contractor/Dita%20Estfarm%20S.R.L.#
![screen shot 2017-05-31 at 5 49 44 pm](https://cloud.githubusercontent.com/assets/12218329/26631217/c0fa3b10-4629-11e7-8ca7-78989b73f771.png)

**Comment by mireille-raad** [comment] 2017-05-31 15:18
damn... thanks for creating this as a seperate repo and for having an API to serve the scraped data.

I'll definitely make sure to present this to PPA or eGov center or whoever works on their open data and ask them to maybe host this script and have the API of court cases for Open Contracting and others to use... this might trigger a different project or other efforts... but thanks for doing this in such modular way.

I don't yet have a full picture how this works... I know the script generates a file and an API that serves the data. My questions are:
- Where does the script sit?
- Is the API reading from the 17GB file or from a database of already parsed information? is it in memory?
- The API is running locally ... you mean on the eGov server now?

What I immagined happened is that you ran the script on your servers, you had some big files to parse, you generated structured data and saved it in a database (probably mongodb) and then you created the API to serve this data to the OC portal.

In order to update court cases... we have 2 options:
- Have a server or a project for court cases that creates an API that OC can connect to without worrying about the how and when.... someone else would be in charge. This is the only way we can have this automated.

- Have someone in PPA, once in a while, use some server to download and process all court cases information and then whatever structure data is made from the script... needs to be uploaded to MongoDB so the local API can serve it to the OC page.

Is this correct or am it too confused... can you kinda clarify the architecture? feel free to just scribble a small graph or chart on how this works.

Sorry for the many questions...

**Comment by anjesh** [comment] 2017-06-01 15:54
Where does the script sit?

* script is in the egov server now, and available at http://moldova-ocds.yipl.com.np/courtsapi/courtcasescount?q=Dita%20estfarm

Is the API reading from the 17GB file or from a database of already parsed information? is it in memory?

* 17GB are files downloaded files from the courts sites, that's how they are maintaining the files in the sites. Database contains the metadata like title, court, dates. 

The API is running locally ... you mean on the eGov server now?

* API is running from eGov server now. By locally i meant, it was accessible using localhost only, but now used proxy to make it available at http://moldova-ocds.yipl.com.np/courtsapi/courtcasescount?q=Dita%20estfarm

Here's the brief system architecture, the data gets stored in mysql database, and available via api. The files (17GB) are not included in the server now due to size. We are only showing the count and titles of the cases for now. 

![image](https://cloud.githubusercontent.com/assets/120488/26677281/f194901a-46ea-11e7-9f9e-f71c3513efc4.png)

The scrapy script takes quite sometime to scrape the courts information and some instruction available in the courts repo.

**Comment by mireille-raad** [comment] 2017-06-01 17:14
Great... maybe you can add this graph to the read me on the "moldova courtcases" repo ... add a line or two of description... since you already have instructions, we can call this documentation.

If someone needs further documentation and wants to really run this, it is a different step/project. 

We can then close this issue :) 🎉

**Comment by anjesh** [comment] 2017-06-22 08:21
Updated https://github.com/younginnovations/moldova-courtcases

**Comment by mireille-raad** [comment] 2017-06-26 07:14
I am checking the link for court cases :( - why is the data no longer showing in the UI? :( - i have a demo... is there any other contractor where court cases show in UI?

Here is the link you shared  http://moldova-demo.yipl.com.np/contracts/contractor/Dita%20Estfarm%20S.R.L.# - i tried for both (open contracting

![screen shot 2017-06-26 at 3 07 11 am](https://user-images.githubusercontent.com/521705/27528079-b34b42aa-5a1c-11e7-8133-7b1ef566ab49.png)

as you can see, the screenshot is not like the one you shared earlier

![c0fa3b10-4629-11e7-8ca7-78989b73f771 1](https://user-images.githubusercontent.com/521705/27528288-be29bda4-5a1d-11e7-9ccf-21c47ec992ff.png)

**Comment by timilsinabishal** [comment] 2017-06-26 08:44
@dc-coder The issue is fixed now. We  had small issue with api service. The given link is showing court cases now. Please have a look.

**Comment by mireille-raad** [comment] 2017-06-26 08:48
phew... thanks a lot :) 

I noticed it is fixed on the demo link - can you please do the same on the opencontracting.date.gov.md as well?

demo link where it works
http://moldova-demo.yipl.com.np/contracts/contractor/Dita%20Estfarm%20S.R.L.#

the date.gov.md link where it does not work yet
http://opencontracting.date.gov.md/contracts/contractor/Dita%20Estfarm%20S.R.L.#

thanks a ton and sorry for bugging...but the handover of portal is tomorrow... so i am preparing presentation and demo.

**Comment by timilsinabishal** [comment] 2017-06-26 09:12
Now showing in http://opencontracting.date.gov.md/contracts/contractor/Dita%20Estfarm%20S.R.L.# too :)

**Comment by mireille-raad** [comment] 2017-06-26 09:17
thanks a lot :) - i promise that me harassing you on this github repo will soon be over :)

**Comment by mireille-raad** [comment] 2017-06-26 09:17
I really appreciate the quick fix

**Closed as completed by mireille-raad** 2017-06-26 09:17 UTC
